title: Seyong Kim
description: Seyong Kim - Ph.D. Student at Yonsei University in wireless communications
url: "https://kim-seyong.github.io"
baseurl: ""
timezone: Korea/Seoul
markdown: kramdown
permalink: pretty
